title: _init()
description: "Initializing.."
author:
  name: "iconrad"
  email: ""
  url: "https://iconrad.github.io/robots.txt/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 40
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "iConrad"
year : "2022"
